num = input("Введите трёхзначное число: ")
print("В вашем числе едениц:")
print(f"{int(num) % 10}")
print("В вашем числе десятков:")
print(f"{(int(num) // 10) % 10}")
print("Сумма цифр в вашем числе:")
print(f"{int(num[0]) + int(num[1]) + int(num[2])}")
print("Произведение цифр в вашем числе:")
print(f"{int(num[0])*int(num[1])*int(num[2])}")
